language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/1359f371f97ea97556e8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
script: python manage.py test