# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_category',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Event_files',
            new_name='Files',
        ),
        migrations.RenameModel(
            old_name='Event_file_type',
            new_name='FileType',
        ),
        migrations.RenameModel(
            old_name='Event_gift',
            new_name='Gift',
        ),
        migrations.RenameModel(
            old_name='Event_own_field',
            new_name='OwnField',
        ),
        migrations.RenameModel(
            old_name='Event_schedule',
            new_name='Schedule',
        ),
        migrations.RenameModel(
            old_name='Event_status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='event_category_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='event_category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='current_participants',
            new_name='maxParticipants',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='event_file_type_id',
            new_name='fileType',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='event_files_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='filetype',
            old_name='event_file_type_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='filetype',
            old_name='file_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='event_gift_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='event_gift_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='event_gift_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='event_gift_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ownfield',
            old_name='own_field_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ownfield',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='ownfield',
            old_name='event_own_field_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ownfield',
            old_name='own_field_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ownfield',
            old_name='own_field_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='event_end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='event_schedule_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='event_schedule_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='event_start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='event_status_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='event_status_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(to='create_form.Event_category', to_field='id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.ForeignKey(to='create_form.Event_status', to_field='id'),
        ),
        migrations.AlterField(
            model_name='files',
            name='fileType',
            field=models.ForeignKey(to='create_form.Event_file_type', to_field='id'),
        ),
    ]
